# You should sync the dependencies from pyproject.toml using 
# sync-deps.py rather than manually adjusting them in this file.
# Don't forget to test afterwards since the script doesn't check
# whether a new package has a conda version ...
name: macrogen
channels:
  - conda-forge
dependencies:
  - python>=3.9,<4.0                    # ^3.9
  - graphviz>=2.4.0
  - numpy>=1.22.4,<2.0                  # ^1.22.4
  - more-itertools>=8.0.2,<9.0          # ^8.0.2
  - networkx>=2.5,<2.6
  - pygraphviz>=1.5,<2.0                # ^1.5
  - ruamel.yaml>=0.16.5,<0.17           # ^0.16.5
  - pyyaml>=5.3,<6.0                    # ^5.3
  - pandas>=1.2.2,<2.0                  # ^1.2.2
  - openpyxl>=3.0.2,<4.0                # ^3.0.2
  - xlrd>=2.0.1,<3.0                    # ^2.0.1
  - lxml>=4.4.2,<5.0                    # ^4.4.2
  - requests>=2.22.0,<3.0               # ^2.22.0
  - colorlog>=4.1.0,<5.0                # ^4.1.0
  - tqdm>=4.41.1,<5.0                   # ^4.41.1
  - cvxpy>=1.0.25,<2.0                  # ^1.0.25
  - cvxopt>=1.2.3,<2.0                  # ^1.2.3
