[tool.poetry]
name = "faust-macrogen"
version = "0.9.2"
description = "Macrogenetic Analysis for the Faust edition"
authors = ["Thorsten Vitt <thorsten.vitt@uni-wuerzburg.de>"]
license = "GPL-3.0"
readme = "README.md"
packages = [
	{ include = "macrogen", from = "src" },
	{ include = "tests", format = "sdist" }
]

[tool.poetry.scripts]
witness-report = 'macrogen.uris:_witness_report'
macrogen-diff = 'macrogen.diff:main'
macrogen = 'macrogen.main:main'


[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.1"
more-itertools = "^8.0.2"
networkx = ">=2.1"
python-igraph = "^0.7.1"
pygraphviz = "^1.5"
"ruamel.yaml" = "^0.16.5"
pyyaml = "^5.3"
pandas = "^0.25.3"
openpyxl = "^3.0.2"
xlrd = "^1.2.0"
lxml = "^4.4.2"
requests = "^2.22.0"
requests-cache = "^0.5.2"
logging-tree = "^1.8"
colorlog = "^4.1.0"
tqdm = "^4.41.1"
cvxpy = "^1.0.25"
cvxopt = "^1.2.3"
flask = {version = "^1.1.1", optional = true}
fastapi = {extras = ["all"], version = "^0.61.0", optional = true}

[tool.poetry.extras]
graphviewer = ["flask"]
fastapi = ["fastapi"]

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
coverage = "^5.0.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
