## Default configuration for the macrogenesis software

# configuration and data files, either paths or URIs
data:       data/xml  # XML Data, this is a folder
logging:    # YAML file with logging configuration
styles:     # YAML file with styling for the graphviz graphs
references: # CSV file featuring manual normalizations for references
bibscores:  # TSV file (FIXME) with scores by source
sigils: http://dev.digital-humanities.de/ci/job/faust-gen-fast/lastSuccessfulBuild/artifact/target/uris.json # JSON file mapping URIs to sigils
paralipomena: http://dev.digital-humanities.de/ci/job/faust-gen-fast/lastSuccessfulBuild/artifact/target/www/data/paralipomena.js # JSON file mapping paralipomena to sources
genetic_bar_graph: # JSON file
report_dir: target/macrogenesis  # where to save reports and graphs

bibliography: https://raw.githubusercontent.com/faustedition/faust-gen-html/master/xslt/bibliography.xml # The bibliography

## Limits
half_interval_correction: 182.5    # if we only have a start or end date, the other limit is max. this many days away
render_node_limit: 1000

## Options for solving the FES
fes_method: baharev   # ip, baharev: exact methods; eades: inexact, list of two: select by fes_threshold
fes_threshold: 64     # if two fes_methods, number of edges above which to select the second one
solvers:              # the first installed solver is chosen. see log message for values.
  - GUROBI
  - auto              # auto = let CVXPY choose
solver_options:
  all:
    max_iters: 10000


## Other data
namespaces:
  f: http://www.faustedition.net/ns
  tei: http://www.tei-c.org/ns/1.0


