version: 1

formatters:
  rich:
    format: "%(message)s"
  tabbed:
    format: "%(asctime)s  %(levelname)-8s %(name)s  %(message)s"

filters:
  display:
    (): macrogen.logging.LevelFilter
    default: WARNING
    levels:
      macrogen.graph: INFO
      macrogen.fes: INFO
      macrogen.witnesses: DEBUG
      "__main__": INFO
  file:
    (): macrogen.logging.LevelFilter
    default: INFO
    levels:
      macrogen.fes: DEBUG
  duplicates:
    (): macrogen.logging.DuplicateFilter

handlers:
  # console:
  #   class: logging.StreamHandler
  #   formatter: colored
  #   filters:
  #     - display
  console:
    class: rich.logging.RichHandler
    log_time_format: "%T"
    rich_tracebacks: true
    formatter: rich
    filters:
      - display
      - duplicates
  file:
    class: logging.FileHandler
    filename: macrogenesis.log
    encoding: utf-8
    mode: w
    formatter: tabbed
    filters:
      - file
      - duplicates

root:
  handlers:
    - console
    - file
  level: DEBUG
